### ISSUE TITLE
Some suggestions for the in the REAME.md

### ISSUE THREAD

**Issue by von-steinkirch** [y-trobinso/tlspretense-service#2]
- Maybe remove sorta PII, for something more generic such as [your-localhost]:[docker-port] or so.
- Maybe mention that the curl tests should be run from another terminal (I was a bit confuse with the make, had to dig into it to see what the file was doing).
- Maybe offer some explanation about what we should be expecting as results (I had to check your old paste to verify that I was doing things right), or how many tests should be run (curl ad infinitum :+1:  )
- Maybe add specific CL expressions under 3 ` to make things more clear.

**Comment by y-trobinso** [comment]
This has been completed. Some of this will be behind a pending blog post.

I've edited your comment to remove a URL that isn't exposed to the outside world. People know it exists, but it won't work in our examples.
